
services:
  odoo18:
    build: .
    container_name: odoo18
    environment:
      - DEBUG=0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "5678:5678"
    volumes:
      - odoo18-data:/var/lib/odoo
      - ./config/odoo:/etc/odoo
      - ./config/requirements:/requirements
      - ./config/log:/var/log/odoo
      - ./addons/custom:/mnt/extra-addons
      - ./addons/enterprise:/mnt/enterprise
      - ./addons/odoo/addons:/odoo18_addons/
  db:
    image: postgres:16.13
    container_name: db_18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data/pgdata  

volumes:
  odoo18-data:
  odoo18-db-data:
